
import Menu.StephensDepotMenu;
import Menu.MenuItem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListSelectionModel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Matt
 */
public class POS_GUI extends javax.swing.JFrame {
    
    public DefaultListModel listModel;
    //public DefaultTableModel tableModelBase; 
    public Order[] orders = new Order[23];
    public EmployeeList employees = new EmployeeList();
    
    /**
     * Creates new form POS_GUI
     */
    public POS_GUI() {
       // tableModelBase = (DefaultTableModel) tableOrder.getModel();
//        Order[] orders = new Order[23];
        initComponents();
        Timer t = new Timer(1000, updateClockAction);
        t.start();
        
        StephensDepotMenu menu = new StephensDepotMenu();
        menu.createMenus();
        
        listModel = new DefaultListModel();
        for(int i = 1; i <= 23; i++){
            listModel.addElement("Table " + i);
        }
        jList2.setModel(listModel);
        jList2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jList2.setSelectedIndex(0);
        
        orders[1] = new Order(1,"This is a note");
        orders[1].addItem( StephensDepotMenu.dinnerMenu.get(1));
        
        DefaultTableModel menuTable1 = (DefaultTableModel) menuTable.getModel();
        menuTable1.setNumRows(0);
        int dinnerSize = StephensDepotMenu.dinnerMenu.size();
        for(int i=0; i < dinnerSize; i++){
            MenuItem obj = StephensDepotMenu.dinnerMenu.get(i);
            menuTable1.addRow(new Object[]{obj.getId(), obj.getName(), obj.description(), obj.getPrice()});
        }
        int breakfastSize = StephensDepotMenu.breakfastMenu.size();
        for(int i=0; i < breakfastSize; i++){
            MenuItem obj = StephensDepotMenu.breakfastMenu.get(i);
            menuTable1.addRow(new Object[]{obj.getId(), obj.getName(), obj.description(), obj.getPrice()});
        }
        int drinkSize = StephensDepotMenu.drinkMenu.size();
        for(int i=0; i < drinkSize; i++){
            MenuItem obj = StephensDepotMenu.drinkMenu.get(i);
            menuTable1.addRow(new Object[]{obj.getId(), obj.getName(), obj.description(), obj.getPrice()});
        }
        menuTable.setModel(menuTable1); 
        
        
        
//        DefaultTableModel tableModel1 = (DefaultTableModel) tableOrder.getModel(); 
//        tableModel1.addRow(new Object[]{"this","is","new"});
////        }
//        tableOrder.setModel(tableModel1);      
    }
    
ActionListener updateClockAction = new ActionListener() {
  public void actionPerformed(ActionEvent e) {
      timeClock.setText(new Date().toString()); 
    }
};

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        tableNumber = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOrder = new javax.swing.JTable();
        addOrderItem = new javax.swing.JButton();
        deleteOrderItem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        orderComment = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        addItem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        menuOrderNumber = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        employeeNumber = new javax.swing.JTextField();
        clockIn = new javax.swing.JButton();
        clockOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        timeClock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NSA Trainee POS");

        jLabel1.setText("Table");

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList2);

        tableNumber.setText("jLabel3");

        tableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Item", "Comments", "Price"
            }
        ));
        jScrollPane2.setViewportView(tableOrder);
        if (tableOrder.getColumnModel().getColumnCount() > 0) {
            tableOrder.getColumnModel().getColumn(0).setPreferredWidth(2);
            tableOrder.getColumnModel().getColumn(0).setHeaderValue("Order Item");
            tableOrder.getColumnModel().getColumn(1).setHeaderValue("Comments");
            tableOrder.getColumnModel().getColumn(2).setHeaderValue("Price");
        }

        addOrderItem.setText("Add Item");
        addOrderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderItemActionPerformed(evt);
            }
        });

        deleteOrderItem.setText("Delete Item");
        deleteOrderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOrderItemActionPerformed(evt);
            }
        });

        jLabel3.setText("Comments:");

        orderComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCommentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(223, 223, 223)
                .addComponent(tableNumber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(deleteOrderItem)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addOrderItem)))
                    .addComponent(jLabel3)
                    .addComponent(orderComment, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tableNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteOrderItem)
                            .addComponent(addOrderItem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Ordering", jPanel1);

        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Notes", "Price"
            }
        ));
        jScrollPane3.setViewportView(menuTable);

        addItem.setText("Add");
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });

        jLabel4.setText("Add Item to order number:");

        jScrollPane4.setViewportView(menuOrderNumber);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addItem))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addItem)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Menu", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Current Orders", jPanel3);

        clockIn.setText("Clock-In");
        clockIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockInActionPerformed(evt);
            }
        });

        clockOut.setText("Clock-Out");
        clockOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockOutActionPerformed(evt);
            }
        });

        jLabel2.setText("Employee ID");

        timeClock.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        timeClock.setText("jLabel3");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeClock)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clockIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clockOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeeNumber))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(timeClock)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clockIn)
                    .addComponent(clockOut))
                .addContainerGap(346, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Time Keeping", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clockInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockInActionPerformed
        // TODO add your handling code here:
        GregorianCalendar now = new GregorianCalendar();
        employees.insert("", Double.parseDouble(employeeNumber.getText()), now.get(Calendar.HOUR_OF_DAY), now.get(Calendar.HOUR_OF_DAY));
    }//GEN-LAST:event_clockInActionPerformed

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        // TODO add your handling code here:
        //DefaultTableModel tableModel1 = tableModelBase;
        DefaultTableModel tableModel1 = (DefaultTableModel) tableOrder.getModel();
        tableModel1.setNumRows(0);
        int tableInt;
        tableInt = jList2.getSelectedIndex();
        tableNumber.setText("Table "+(tableInt + 1));
        if(orders[tableInt] != null){
            ArrayList <MenuItem> orderItems = orders[tableInt].getItems();
            Iterator<MenuItem> it = orderItems.iterator();
            int i = 0;
            while(it.hasNext())
            {
                MenuItem obj = it.next();
                tableModel1.addRow(new Object[]{obj.getName(), obj.description(), obj.getPrice()});

                //Do something with obj
            }
            
        }else{
            orders[tableInt] = new Order(tableInt, "");
        }
        orderComment.setText(orders[tableInt].getComment());
        tableOrder.setModel(tableModel1); 
        
    }//GEN-LAST:event_jList2ValueChanged

    private void addOrderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderItemActionPerformed
        // TODO add your handling code here:
        menuOrderNumber.setText(Integer.toString(jList2.getSelectedIndex()));
        jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_addOrderItemActionPerformed

    private void orderCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCommentActionPerformed
        // TODO add your handling code here:
        int tableInt;
        tableInt = jList2.getSelectedIndex();
        orders[tableInt].setComment(orderComment.getText());
    }//GEN-LAST:event_orderCommentActionPerformed

    private void clockOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockOutActionPerformed
        // TODO add your handling code here:
        GregorianCalendar now = new GregorianCalendar();
        employees.insert("", Double.parseDouble(employeeNumber.getText()), now.get(Calendar.HOUR_OF_DAY), now.get(Calendar.HOUR_OF_DAY));
    }//GEN-LAST:event_clockOutActionPerformed

    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
        int orderNumber = Integer.parseInt(menuOrderNumber.getText());
        int itemId = menuTable.getSelectedRow();
        if(orders[orderNumber] == null){
            orders[orderNumber] = new Order(orderNumber, "");
        }
        if(itemId <= 34){
            orders[orderNumber].addItem(StephensDepotMenu.dinnerMenu.get(itemId));
        }
        if(itemId >= 35 && itemId <= 56){
            orders[orderNumber].addItem(StephensDepotMenu.breakfastMenu.get((itemId - 34)));
        }
        if(itemId >= 57){
            orders[orderNumber].addItem(StephensDepotMenu.drinkMenu.get((itemId - 56)));
        }
        jTabbedPane1.setSelectedIndex(0);
        jList2.setSelectedIndex(orderNumber);
// TODO add your handling code here:
    }//GEN-LAST:event_addItemActionPerformed

    private void deleteOrderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOrderItemActionPerformed
        // TODO add your handling code here:
        int orderNumber = jList2.getSelectedIndex();
        int orderItemId = tableOrder.getSelectedRow();
        orders[orderNumber].deleteItem(orderItemId);
    }//GEN-LAST:event_deleteOrderItemActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS_GUI().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItem;
    private javax.swing.JButton addOrderItem;
    private javax.swing.JButton clockIn;
    private javax.swing.JButton clockOut;
    private javax.swing.JButton deleteOrderItem;
    private javax.swing.JTextField employeeNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane menuOrderNumber;
    private javax.swing.JTable menuTable;
    private javax.swing.JTextField orderComment;
    private javax.swing.JLabel tableNumber;
    private javax.swing.JTable tableOrder;
    private javax.swing.JLabel timeClock;
    // End of variables declaration//GEN-END:variables
}
